// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbo8arrEOvaJHfbbBQioYBft4UHyZqVgQ',
    appId: '1:822171861507:web:10302e875e8bdf84188436',
    messagingSenderId: '822171861507',
    projectId: 'chat-app-cc7a4',
    authDomain: 'chat-app-cc7a4.firebaseapp.com',
    storageBucket: 'chat-app-cc7a4.appspot.com',
    measurementId: 'G-Q6YKZVR1X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5iQ2XjaxNdI5U0Btas458uoxEnwVBaj4',
    appId: '1:822171861507:android:4747b747c05e3324188436',
    messagingSenderId: '822171861507',
    projectId: 'chat-app-cc7a4',
    storageBucket: 'chat-app-cc7a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kx2v3qiIaXZtngGMhkfSa4PfvCEtt6U',
    appId: '1:822171861507:ios:5918fd6695cf593c188436',
    messagingSenderId: '822171861507',
    projectId: 'chat-app-cc7a4',
    storageBucket: 'chat-app-cc7a4.appspot.com',
    iosClientId:
        '822171861507-eujbdqfka964ksarthu6aofv30mpbg9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kx2v3qiIaXZtngGMhkfSa4PfvCEtt6U',
    appId: '1:822171861507:ios:5918fd6695cf593c188436',
    messagingSenderId: '822171861507',
    projectId: 'chat-app-cc7a4',
    storageBucket: 'chat-app-cc7a4.appspot.com',
    iosClientId:
        '822171861507-eujbdqfka964ksarthu6aofv30mpbg9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
